version: '3'
services:
    uwsgi_flask_backend:
        image: sgasse/uwsgi_flask_backend
        build:
            context: uwsgi_flask_backend
        volumes:
            - ./data/sqlite_data:/db

    nginx_frontend:
        image: nginx:1.13-alpine
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - uwsgi_flask_backend
        ports:
            - 80:80
